version: '3'
networks:
  homepage:
    driver: bridge
services:
  nginx:
    container_name: homepage-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - homepage
    depends_on:
      - watchlist-api-1
      - watchlist-api-2
      - profiles-api-1
      - profiles-api-2
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: homepage-nginx-exporter
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://homepage-nginx:8080/stub_status
    networks:
      - homepage
    depends_on:
      - nginx
  watchlist-api-1:
    container_name: watchlist-api-1
    build: ./WatchList-API
    environment:
      - MONGO_URI=mongodb://homepage-mongo:27017
    volumes:
      - ./WatchList-API:/app
    networks:
      - homepage
    depends_on:
      - broker
  watchlist-api-2:
    container_name: watchlist-api-2
    build: ./WatchList-API
    environment:
      - MONGO_URI=mongodb://homepage-mongo:27017
    volumes:
      - ./WatchList-API:/app
    networks:
      - homepage
    depends_on:
      - broker
  profiles-api-1:
    container_name: profiles-api-1
    build: ./Profiles-API
    environment:
      - MONGO_URI=mongodb://homepage-mongo:27017
    volumes:
      - ./Profiles-API:/app
    networks:
      - homepage
    depends_on:
      - broker
  profiles-api-2:
    container_name: profiles-api-2
    build: ./Profiles-API
    environment:
      - MONGO_URI=mongodb://homepage-mongo:27017
    volumes:
      - ./Profiles-API:/app
    networks:
      - homepage
    depends_on:
      - broker
  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: homepage-kafka-exporter
    command: --kafka.server=broker:29092
    ports:
      - "9308:9308"
    networks:
      - homepage
    depends_on:
      - profiles-api-1 # This is just to make sure the broker is up and running
  broker:
    container_name: homepage-broker
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092" # Main port for Kafka
      # - "9092:9092"
      # - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: homepage-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_INTERNAL://homepage-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - homepage
  zookeeper:
    container_name: homepage-zookeeper
    image: confluentinc/cp-zookeeper:latest
    # ports:
      # - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - homepage
  watchlist-controller:
    container_name: watchlist-controller
    build: ./WatchList-Controller
    environment:
      - MONGO_URI=mongodb://homepage-mongo:27017
      - MOVIE_DB_API_KEY=959d7da058d687321c67d47b52e38e7c
    volumes:
      - ./WatchList-Controller:/app
    networks:
      - homepage
    depends_on:
      - broker
  profiles-controller:
    container_name: profiles-controller
    build: ./Profiles-Controller
    environment:
      - MONGO_URI=mongodb://homepage-mongo:27017
    volumes:
      - ./Profiles-Controller:/app
    networks:
      - homepage
    depends_on:
      - broker
  mongo:
    container_name: homepage-mongo
    image: mongo:latest
    ports:
      - "2718:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - homepage
  mongo-exporter:
    container_name: homepage-mongo-exporter
    image: bitnami/mongodb-exporter:latest
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://homepage-mongo:27017
    networks:
      - homepage
    depends_on:
      - mongo
  prometheus: 
    container_name: homepage-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - homepage
    depends_on:
      - watchlist-api-1
      - watchlist-api-2
      - profiles-api-1
      - profiles-api-2
      - watchlist-controller
      - profiles-controller
      - mongo-exporter
      - nginx-exporter
      - kafka-exporter

volumes:
  mongodb_data: