global:
  scrape_interval: 15s
  scrape_timeout: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "api-services"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'profiles-api-1:8000'
        - 'profiles-api-2:8000'
        - 'watchList-api-1:8000'
        - 'watchList-api-2:8000'
  - job_name: "controllers"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'profiles-controller:8000'
        - 'watchList-controller:8000'
  - job_name: "mynginx"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'homepage-nginx-exporter:9113'
  - job_name: "kafka"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'homepage-kafka-exporter:9308'
  - job_name: "mongodb"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'homepage-mongo-exporter:9216'

remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 801256
      password: eyJrIjoiZWYxMzFiNzI3YjIzOGY3MGVkODc0MDM1N2VmM2Y4NDhjOTI5MDdmNSIsIm4iOiJNZXRyaWNzS2V5IiwiaWQiOjgwNjUwOX0=