global:
  scrape_interval: 15s
  scrape_timeout: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "api-services"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'retro-games-api-1:8000'
        - 'retro-games-api-2:8000'
        - 'retro-games-email-service:8000'
  - job_name: "mongodb"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'mongodb:27017'
  - job_name: "mynginx"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'mynginx:80'
  - job_name: "kafka"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 'kafka-exporter:9308'

remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 801256
      password: eyJrIjoiZWYxMzFiNzI3YjIzOGY3MGVkODc0MDM1N2VmM2Y4NDhjOTI5MDdmNSIsIm4iOiJNZXRyaWNzS2V5IiwiaWQiOjgwNjUwOX0=